/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Connection.xs. Do not edit this file, edit Connection.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Connection.xs"
#include "module.h"

#line 13 "Connection.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 155 "Connection.c"

XS_EUPXS(XS_Purple__Connection_get_account); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_get_account)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "gc");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	Purple__Account	RETVAL;

	RETVAL = purple_connection_get_account(gc);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Account");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Connection_get_password); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_get_password)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "gc");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_connection_get_password(gc);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Connection_get_display_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_get_display_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "gc");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_connection_get_display_name(gc);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Connection_notice); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_notice)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "gc, text");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	const char *	text = (const char *)SvPV_nolen(ST(1))
;

	purple_connection_notice(gc, text);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Connection_error); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_error)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "gc, reason");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	const char *	reason = (const char *)SvPV_nolen(ST(1))
;

	purple_connection_error(gc, reason);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Connection_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "gc");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;

	purple_connection_destroy(gc);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Connection_set_state); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_set_state)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "gc, state");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	Purple__ConnectionState	state = (Purple__ConnectionState)SvIV(ST(1))
;

	purple_connection_set_state(gc, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Connection_set_account); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_set_account)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "gc, account");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	Purple__Account	account = purple_perl_ref_object(ST(1))
;

	purple_connection_set_account(gc, account);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Connection_set_display_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_set_display_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "gc, name");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;

	purple_connection_set_display_name(gc, name);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Connection_get_state); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connection_get_state)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "gc");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	Purple__ConnectionState	RETVAL;
	dXSTARG;

	RETVAL = purple_connection_get_state(gc);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Connections_disconnect_all); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connections_disconnect_all)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	purple_connections_disconnect_all();
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Connections_get_all); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connections_get_all)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 75 "Connection.xs"
	GList *l;
#line 364 "Connection.c"
#line 77 "Connection.xs"
	for (l = purple_connections_get_all(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Connection")));
	}
#line 369 "Connection.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Connections_get_connecting); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connections_get_connecting)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 84 "Connection.xs"
	GList *l;
#line 387 "Connection.c"
#line 86 "Connection.xs"
	for (l = purple_connections_get_connecting(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Connection")));
	}
#line 392 "Connection.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Connections_get_handle); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Connections_get_handle)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_connections_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Purple__Connection); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Purple__Connection)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Purple::Connection::get_account", XS_Purple__Connection_get_account, file, "$");
        (void)newXSproto_portable("Purple::Connection::get_password", XS_Purple__Connection_get_password, file, "$");
        (void)newXSproto_portable("Purple::Connection::get_display_name", XS_Purple__Connection_get_display_name, file, "$");
        (void)newXSproto_portable("Purple::Connection::notice", XS_Purple__Connection_notice, file, "$$");
        (void)newXSproto_portable("Purple::Connection::error", XS_Purple__Connection_error, file, "$$");
        (void)newXSproto_portable("Purple::Connection::destroy", XS_Purple__Connection_destroy, file, "$");
        (void)newXSproto_portable("Purple::Connection::set_state", XS_Purple__Connection_set_state, file, "$$");
        (void)newXSproto_portable("Purple::Connection::set_account", XS_Purple__Connection_set_account, file, "$$");
        (void)newXSproto_portable("Purple::Connection::set_display_name", XS_Purple__Connection_set_display_name, file, "$$");
        (void)newXSproto_portable("Purple::Connection::get_state", XS_Purple__Connection_get_state, file, "$");
        (void)newXSproto_portable("Purple::Connections::disconnect_all", XS_Purple__Connections_disconnect_all, file, "");
        (void)newXSproto_portable("Purple::Connections::get_all", XS_Purple__Connections_get_all, file, "");
        (void)newXSproto_portable("Purple::Connections::get_connecting", XS_Purple__Connections_get_connecting, file, "");
        (void)newXSproto_portable("Purple::Connections::get_handle", XS_Purple__Connections_get_handle, file, "");

    /* Initialisation Section */

#line 7 "Connection.xs"
{
	HV *stash = gv_stashpv("Purple::Connection::State", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_##name}
		const_iv(DISCONNECTED),
		const_iv(CONNECTED),
		const_iv(CONNECTING),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 467 "Connection.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

