/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Conversation.xs. Do not edit this file, edit Conversation.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Conversation.xs"
#include "module.h"

#line 13 "Conversation.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 155 "Conversation.c"

XS_EUPXS(XS_Purple_get_ims); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple_get_ims)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 97 "Conversation.xs"
	GList *l;
#line 168 "Conversation.c"
#line 99 "Conversation.xs"
	for (l = purple_get_ims(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Conversation")));
	}
#line 173 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple_get_conversations); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple_get_conversations)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 106 "Conversation.xs"
	GList *l;
#line 191 "Conversation.c"
#line 108 "Conversation.xs"
	for (l = purple_get_conversations(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Conversation")));
	}
#line 196 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple_get_chats); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple_get_chats)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 115 "Conversation.xs"
	GList *l;
#line 214 "Conversation.c"
#line 117 "Conversation.xs"
	for (l = purple_get_chats(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Conversation")));
	}
#line 219 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple_find_conversation_with_account); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple_find_conversation_with_account)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "type, name, account");
    {
	Purple__ConversationType	type = (Purple__ConversationType)SvIV(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;
	Purple__Account	account = purple_perl_ref_object(ST(2))
;
	Purple__Conversation	RETVAL;

	RETVAL = purple_find_conversation_with_account(type, name, account);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversations_get_handle); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversations_get_handle)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_conversations_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;

	purple_conversation_destroy(conv);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_get_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__ConversationType	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_type(conv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_get_account); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_account)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__Account	RETVAL;

	RETVAL = purple_conversation_get_account(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Account");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_get_gc); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_gc)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__Connection	RETVAL;

	RETVAL = purple_conversation_get_gc(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Connection");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_set_title); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_set_title)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "conv, title");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	title = (const char *)SvPV_nolen(ST(1))
;

	purple_conversation_set_title(conv, title);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_get_title); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_title)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_title(conv);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_autoset_title); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_autoset_title)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;

	purple_conversation_autoset_title(conv);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_set_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_set_name)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "conv, name");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;

	purple_conversation_set_name(conv, name);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_get_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_name(conv);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_set_logging); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_set_logging)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "conv, log");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	gboolean	log = (bool)SvTRUE(ST(1))
;

	purple_conversation_set_logging(conv, log);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_is_logging); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_is_logging)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_conversation_is_logging(conv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_get_im_data); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_im_data)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__Conversation__IM	RETVAL;

	RETVAL = purple_conversation_get_im_data(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation::IM");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_get_chat_data); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_chat_data)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__Conversation__Chat	RETVAL;

	RETVAL = purple_conversation_get_chat_data(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation::Chat");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_get_data); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_data)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "conv, key");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	key = (const char *)SvPV_nolen(ST(1))
;
	gpointer	RETVAL;

	RETVAL = purple_conversation_get_data(conv, key);
	ST(0) = purple_perl_bless_object(RETVAL, "gpointer");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_get_features); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_get_features)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__ConnectionFlags	RETVAL;
	dXSTARG;

	RETVAL = purple_conversation_get_features(conv);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_has_focus); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_has_focus)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_conversation_has_focus(conv);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_update); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_update)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "conv, type");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__ConvUpdateType	type = (Purple__ConvUpdateType)SvIV(ST(1))
;

	purple_conversation_update(conv, type);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_new)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "class, type, account, name");
    {
	Purple__ConversationType	type = (Purple__ConversationType)SvIV(ST(1))
;
	Purple__Account	account = purple_perl_ref_object(ST(2))
;
	const char *	name = (const char *)SvPV_nolen(ST(3))
;
	Purple__Conversation	RETVAL;

	RETVAL = purple_conversation_new(type, account, name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_set_account); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_set_account)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "conv, account");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__Account	account = purple_perl_ref_object(ST(1))
;

	purple_conversation_set_account(conv, account);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_write)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "conv, who, message, flags, mtime");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	who = (const char *)SvPV_nolen(ST(1))
;
	const char *	message = (const char *)SvPV_nolen(ST(2))
;
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(3))
;
	time_t	mtime = (time_t)SvIV(ST(4))
;

	purple_conversation_write(conv, who, message, flags, mtime);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_do_command); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_do_command)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "conv, cmdline, markup, error");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	cmdline = (const char *)SvPV_nolen(ST(1))
;
	const char *	markup = (const char *)SvPV_nolen(ST(2))
;
	char **	error = INT2PTR(char **,SvIV(ST(3)))
;
	gboolean	RETVAL;

	RETVAL = purple_conversation_do_command(conv, cmdline, markup, error);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__IM_get_conversation); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_get_conversation)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	Purple__Conversation	RETVAL;

	RETVAL = purple_conv_im_get_conversation(im);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__IM_set_icon); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_set_icon)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "im, icon");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	Purple__Buddy__Icon	icon = purple_perl_ref_object(ST(1))
;

	purple_conv_im_set_icon(im, icon);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_get_icon); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_get_icon)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	Purple__Buddy__Icon	RETVAL;

	RETVAL = purple_conv_im_get_icon(im);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Buddy::Icon");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__IM_set_typing_state); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_set_typing_state)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "im, state");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	Purple__TypingState	state = (Purple__TypingState)SvIV(ST(1))
;

	purple_conv_im_set_typing_state(im, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_get_typing_state); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_get_typing_state)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	Purple__TypingState	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_typing_state(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__IM_start_typing_timeout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_start_typing_timeout)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "im, timeout");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	int	timeout = (int)SvIV(ST(1))
;

	purple_conv_im_start_typing_timeout(im, timeout);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_stop_typing_timeout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_stop_typing_timeout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;

	purple_conv_im_stop_typing_timeout(im);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_get_typing_timeout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_get_typing_timeout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	guint	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_typing_timeout(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__IM_set_type_again); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_set_type_again)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "im, val");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	time_t	val = (time_t)SvIV(ST(1))
;

	purple_conv_im_set_type_again(im, val);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_get_type_again); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_get_type_again)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	time_t	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_type_again(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__IM_start_send_typed_timeout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_start_send_typed_timeout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;

	purple_conv_im_start_send_typed_timeout(im);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_stop_send_typed_timeout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_stop_send_typed_timeout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;

	purple_conv_im_stop_send_typed_timeout(im);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_get_send_typed_timeout); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_get_send_typed_timeout)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	guint	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_im_get_send_typed_timeout(im);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__IM_update_typing); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_update_typing)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "im");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;

	purple_conv_im_update_typing(im);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_send); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_send)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "im, message");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	const char *	message = (const char *)SvPV_nolen(ST(1))
;

	purple_conv_im_send(im, message);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_send_with_flags); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_send_with_flags)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "im, message, flags");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	const char *	message = (const char *)SvPV_nolen(ST(1))
;
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(2))
;

	purple_conv_im_send_with_flags(im, message, flags);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__IM_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__IM_write)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "im, who, message, flags, mtime");
    {
	Purple__Conversation__IM	im = purple_perl_ref_object(ST(0))
;
	const char *	who = (const char *)SvPV_nolen(ST(1))
;
	const char *	message = (const char *)SvPV_nolen(ST(2))
;
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(3))
;
	time_t	mtime = (time_t)SvIV(ST(4))
;

	purple_conv_im_write(im, who, message, flags, mtime);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation_present_error); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_present_error)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "who, account, what");
    {
	const char *	who = (const char *)SvPV_nolen(ST(0))
;
	Purple__Account	account = purple_perl_ref_object(ST(1))
;
	const char *	what = (const char *)SvPV_nolen(ST(2))
;
	gboolean	RETVAL;

	RETVAL = purple_conv_present_error(who, account, what);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation_custom_smiley_close); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation_custom_smiley_close)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "conv, smile");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	const char *	smile = (const char *)SvPV_nolen(ST(1))
;

	purple_conv_custom_smiley_close(conv, smile);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_get_conversation); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_get_conversation)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	Purple__Conversation	RETVAL;

	RETVAL = purple_conv_chat_get_conversation(chat);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_set_users); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_set_users)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, users");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	SV *	users = ST(1)
;
#line 345 "Conversation.xs"
	GList *l, *t_GL;
	int i, t_len;
#line 1059 "Conversation.c"
#line 348 "Conversation.xs"
	t_GL = NULL;
	t_len = av_len((AV *)SvRV(users));

	for (i = 0; i <= t_len; i++)
		t_GL = g_list_append(t_GL, SvPVutf8_nolen(*av_fetch((AV *)SvRV(users), i, 0)));

	for (l = purple_conv_chat_set_users(chat, t_GL); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1070 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Conversation__Chat_get_users); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_get_users)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
#line 362 "Conversation.xs"
	GList *l;
#line 1090 "Conversation.c"
#line 364 "Conversation.xs"
	for (l = purple_conv_chat_get_users(chat); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1095 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Conversation__Chat_ignore); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_ignore)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, name");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;

	purple_conv_chat_ignore(chat, name);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_unignore); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_unignore)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, name");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;

	purple_conv_chat_unignore(chat, name);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_set_ignored); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_set_ignored)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, ignored");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	SV *	ignored = ST(1)
;
#line 383 "Conversation.xs"
	GList *l, *t_GL;
	int i, t_len;
#line 1154 "Conversation.c"
#line 386 "Conversation.xs"
	t_GL = NULL;
	t_len = av_len((AV *)SvRV(ignored));

	for (i = 0; i <= t_len; i++)
		t_GL = g_list_append(t_GL, SvPVutf8_nolen(*av_fetch((AV *)SvRV(ignored), i, 0)));

	for (l = purple_conv_chat_set_ignored(chat, t_GL); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1165 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Conversation__Chat_get_ignored); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_get_ignored)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
#line 400 "Conversation.xs"
	GList *l;
#line 1185 "Conversation.c"
#line 402 "Conversation.xs"
	for (l = purple_conv_chat_get_ignored(chat); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::ListEntry")));
	}
#line 1190 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Conversation__Chat_get_topic); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_get_topic)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_get_topic(chat);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_set_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_set_id)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, id");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	int	id = (int)SvIV(ST(1))
;

	purple_conv_chat_set_id(chat, id);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_get_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_get_id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_get_id(chat);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_send); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_send)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, message");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	message = (const char *)SvPV_nolen(ST(1))
;

	purple_conv_chat_send(chat, message);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_send_with_flags); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_send_with_flags)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "chat, message, flags");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	message = (const char *)SvPV_nolen(ST(1))
;
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(2))
;

	purple_conv_chat_send_with_flags(chat, message, flags);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_write)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "chat, who, message, flags, mtime");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	who = (const char *)SvPV_nolen(ST(1))
;
	const char *	message = (const char *)SvPV_nolen(ST(2))
;
	Purple__MessageFlags	flags = (Purple__MessageFlags)SvIV(ST(3))
;
	time_t	mtime = (time_t)SvIV(ST(4))
;

	purple_conv_chat_write(chat, who, message, flags, mtime);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_add_users); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_add_users)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "chat, users, extra_msgs, flags, new_arrivals");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	SV *	users = ST(1)
;
	SV *	extra_msgs = ST(2)
;
	SV *	flags = ST(3)
;
	gboolean	new_arrivals = (bool)SvTRUE(ST(4))
;
#line 446 "Conversation.xs"
	GList *t_GL_users, *t_GL_extra_msgs, *t_GL_flags;
	int i, t_len;
#line 1337 "Conversation.c"
#line 449 "Conversation.xs"
	t_GL_users = NULL;
	t_len = av_len((AV *)SvRV(users));

	for (i = 0; i <= t_len; i++)
		t_GL_users = g_list_append(t_GL_users, SvPVutf8_nolen(*av_fetch((AV *)SvRV(users), i, 0)));

	t_GL_flags = NULL;
	t_len = av_len((AV *)SvRV(flags));

	for (i = 0; i <= t_len; i++)
		t_GL_flags = g_list_append(t_GL_flags, SvPVutf8_nolen(*av_fetch((AV *)SvRV(flags), i, 0)));

	t_GL_extra_msgs = NULL;
	t_len = av_len((AV *)SvRV(extra_msgs));

	for (i = 0; i <= t_len; i++)
		t_GL_extra_msgs = g_list_append(t_GL_extra_msgs, SvPVutf8_nolen(*av_fetch((AV *)SvRV(extra_msgs), i, 0)));

	purple_conv_chat_add_users(chat, t_GL_users, t_GL_extra_msgs, t_GL_flags, new_arrivals);

	g_list_free(t_GL_users);
	g_list_free(t_GL_extra_msgs);
	g_list_free(t_GL_flags);
#line 1362 "Conversation.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Conversation__Chat_find_user); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_find_user)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, user");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	user = (const char *)SvPV_nolen(ST(1))
;
	gboolean	RETVAL;

	RETVAL = purple_conv_chat_find_user(chat, user);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_clear_users); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_clear_users)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;

	purple_conv_chat_clear_users(chat);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_set_nick); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_set_nick)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, nick");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	nick = (const char *)SvPV_nolen(ST(1))
;

	purple_conv_chat_set_nick(chat, nick);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_get_nick); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_get_nick)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_get_nick(chat);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_purple_find_chat); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_purple_find_chat)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "gc, id");
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0))
;
	int	id = (int)SvIV(ST(1))
;
	Purple__Conversation	RETVAL;

	RETVAL = purple_find_chat(gc, id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_left); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_left)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;

	purple_conv_chat_left(chat);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Conversation__Chat_has_left); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_has_left)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "chat");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_conv_chat_has_left(chat);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_cb_find); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_cb_find)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "chat, name");
    {
	Purple__Conversation__Chat	chat = purple_perl_ref_object(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;
	Purple__Conversation__ChatBuddy	RETVAL;

	RETVAL = purple_conv_chat_cb_find(chat, name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation::ChatBuddy");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_cb_get_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_cb_get_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cb");
    {
	Purple__Conversation__ChatBuddy	cb = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_conv_chat_cb_get_name(cb);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Conversation__Chat_cb_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Conversation__Chat_cb_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cb");
    {
	Purple__Conversation__ChatBuddy	cb = purple_perl_ref_object(ST(0))
;

	purple_conv_chat_cb_destroy(cb);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Purple__Conversation); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Purple__Conversation)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Purple::get_ims", XS_Purple_get_ims, file, "");
        (void)newXSproto_portable("Purple::get_conversations", XS_Purple_get_conversations, file, "");
        (void)newXSproto_portable("Purple::get_chats", XS_Purple_get_chats, file, "");
        (void)newXSproto_portable("Purple::find_conversation_with_account", XS_Purple_find_conversation_with_account, file, "$$$");
        (void)newXSproto_portable("Purple::Conversations::get_handle", XS_Purple__Conversations_get_handle, file, "");
        (void)newXSproto_portable("Purple::Conversation::destroy", XS_Purple__Conversation_destroy, file, "$");
        (void)newXSproto_portable("Purple::Conversation::get_type", XS_Purple__Conversation_get_type, file, "$");
        (void)newXSproto_portable("Purple::Conversation::get_account", XS_Purple__Conversation_get_account, file, "$");
        (void)newXSproto_portable("Purple::Conversation::get_gc", XS_Purple__Conversation_get_gc, file, "$");
        (void)newXSproto_portable("Purple::Conversation::set_title", XS_Purple__Conversation_set_title, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::get_title", XS_Purple__Conversation_get_title, file, "$");
        (void)newXSproto_portable("Purple::Conversation::autoset_title", XS_Purple__Conversation_autoset_title, file, "$");
        (void)newXSproto_portable("Purple::Conversation::set_name", XS_Purple__Conversation_set_name, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::get_name", XS_Purple__Conversation_get_name, file, "$");
        (void)newXSproto_portable("Purple::Conversation::set_logging", XS_Purple__Conversation_set_logging, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::is_logging", XS_Purple__Conversation_is_logging, file, "$");
        (void)newXSproto_portable("Purple::Conversation::get_im_data", XS_Purple__Conversation_get_im_data, file, "$");
        (void)newXSproto_portable("Purple::Conversation::get_chat_data", XS_Purple__Conversation_get_chat_data, file, "$");
        (void)newXSproto_portable("Purple::Conversation::get_data", XS_Purple__Conversation_get_data, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::get_features", XS_Purple__Conversation_get_features, file, "$");
        (void)newXSproto_portable("Purple::Conversation::has_focus", XS_Purple__Conversation_has_focus, file, "$");
        (void)newXSproto_portable("Purple::Conversation::update", XS_Purple__Conversation_update, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::new", XS_Purple__Conversation_new, file, "$$$$");
        (void)newXSproto_portable("Purple::Conversation::set_account", XS_Purple__Conversation_set_account, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::write", XS_Purple__Conversation_write, file, "$$$$$");
        (void)newXSproto_portable("Purple::Conversation::do_command", XS_Purple__Conversation_do_command, file, "$$$$");
        (void)newXSproto_portable("Purple::Conversation::IM::get_conversation", XS_Purple__Conversation__IM_get_conversation, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::set_icon", XS_Purple__Conversation__IM_set_icon, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::IM::get_icon", XS_Purple__Conversation__IM_get_icon, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::set_typing_state", XS_Purple__Conversation__IM_set_typing_state, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::IM::get_typing_state", XS_Purple__Conversation__IM_get_typing_state, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::start_typing_timeout", XS_Purple__Conversation__IM_start_typing_timeout, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::IM::stop_typing_timeout", XS_Purple__Conversation__IM_stop_typing_timeout, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::get_typing_timeout", XS_Purple__Conversation__IM_get_typing_timeout, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::set_type_again", XS_Purple__Conversation__IM_set_type_again, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::IM::get_type_again", XS_Purple__Conversation__IM_get_type_again, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::start_send_typed_timeout", XS_Purple__Conversation__IM_start_send_typed_timeout, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::stop_send_typed_timeout", XS_Purple__Conversation__IM_stop_send_typed_timeout, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::get_send_typed_timeout", XS_Purple__Conversation__IM_get_send_typed_timeout, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::update_typing", XS_Purple__Conversation__IM_update_typing, file, "$");
        (void)newXSproto_portable("Purple::Conversation::IM::send", XS_Purple__Conversation__IM_send, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::IM::send_with_flags", XS_Purple__Conversation__IM_send_with_flags, file, "$$$");
        (void)newXSproto_portable("Purple::Conversation::IM::write", XS_Purple__Conversation__IM_write, file, "$$$$$");
        (void)newXSproto_portable("Purple::Conversation::present_error", XS_Purple__Conversation_present_error, file, "$$$");
        (void)newXSproto_portable("Purple::Conversation::custom_smiley_close", XS_Purple__Conversation_custom_smiley_close, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::get_conversation", XS_Purple__Conversation__Chat_get_conversation, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::set_users", XS_Purple__Conversation__Chat_set_users, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::get_users", XS_Purple__Conversation__Chat_get_users, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::ignore", XS_Purple__Conversation__Chat_ignore, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::unignore", XS_Purple__Conversation__Chat_unignore, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::set_ignored", XS_Purple__Conversation__Chat_set_ignored, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::get_ignored", XS_Purple__Conversation__Chat_get_ignored, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::get_topic", XS_Purple__Conversation__Chat_get_topic, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::set_id", XS_Purple__Conversation__Chat_set_id, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::get_id", XS_Purple__Conversation__Chat_get_id, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::send", XS_Purple__Conversation__Chat_send, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::send_with_flags", XS_Purple__Conversation__Chat_send_with_flags, file, "$$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::write", XS_Purple__Conversation__Chat_write, file, "$$$$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::add_users", XS_Purple__Conversation__Chat_add_users, file, "$$$$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::find_user", XS_Purple__Conversation__Chat_find_user, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::clear_users", XS_Purple__Conversation__Chat_clear_users, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::set_nick", XS_Purple__Conversation__Chat_set_nick, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::get_nick", XS_Purple__Conversation__Chat_get_nick, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::purple_find_chat", XS_Purple__Conversation__Chat_purple_find_chat, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::left", XS_Purple__Conversation__Chat_left, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::has_left", XS_Purple__Conversation__Chat_has_left, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::cb_find", XS_Purple__Conversation__Chat_cb_find, file, "$$");
        (void)newXSproto_portable("Purple::Conversation::Chat::cb_get_name", XS_Purple__Conversation__Chat_cb_get_name, file, "$");
        (void)newXSproto_portable("Purple::Conversation::Chat::cb_destroy", XS_Purple__Conversation__Chat_cb_destroy, file, "$");

    /* Initialisation Section */

#line 7 "Conversation.xs"
{
	HV *type_stash = gv_stashpv("Purple::Conversation::Type", 1);
	HV *update_stash = gv_stashpv("Purple::Conversation::Update::Type", 1);
	HV *typing_stash = gv_stashpv("Purple::Conversation::TypingState", 1);
	HV *flags_stash = gv_stashpv("Purple::Conversation::Flags", 1);
	HV *cbflags_stash = gv_stashpv("Purple::Conversation::ChatBuddy::Flags", 1);

	static const constiv *civ, type_const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_CONV_TYPE_##name}
		const_iv(UNKNOWN),
		const_iv(IM),
		const_iv(CHAT),
		const_iv(MISC),
		const_iv(ANY),
	};
	static const constiv update_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_CONV_UPDATE_##name}
		const_iv(ADD),
		const_iv(REMOVE),
		const_iv(ACCOUNT),
		const_iv(TYPING),
		const_iv(UNSEEN),
		const_iv(LOGGING),
		const_iv(TOPIC),
/*
		const_iv(ONLINE),
		const_iv(OFFLINE),
*/
		const_iv(AWAY),
		const_iv(ICON),
		const_iv(TITLE),
		const_iv(CHATLEFT),
		const_iv(FEATURES),
	};
	static const constiv typing_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_##name}
		const_iv(NOT_TYPING),
		const_iv(TYPING),
		const_iv(TYPED),
	};
	static const constiv flags_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_MESSAGE_##name}
		const_iv(SEND),
		const_iv(RECV),
		const_iv(SYSTEM),
		const_iv(AUTO_RESP),
		const_iv(ACTIVE_ONLY),
		const_iv(NICK),
		const_iv(NO_LOG),
		const_iv(WHISPER),
		const_iv(ERROR),
		const_iv(DELAYED),
		const_iv(RAW),
		const_iv(IMAGES),
		const_iv(NOTIFY),
		const_iv(NO_LINKIFY),
	};
	static const constiv cbflags_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_CBFLAGS_##name}
		const_iv(NONE),
		const_iv(VOICE),
		const_iv(HALFOP),
		const_iv(OP),
		const_iv(FOUNDER),
		const_iv(TYPING),
	};

	for (civ = type_const_iv + sizeof(type_const_iv) / sizeof(type_const_iv[0]); civ-- > type_const_iv; )
		newCONSTSUB(type_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = update_const_iv + sizeof(update_const_iv) / sizeof(update_const_iv[0]); civ-- > update_const_iv; )
		newCONSTSUB(update_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = typing_const_iv + sizeof(typing_const_iv) / sizeof(typing_const_iv[0]); civ-- > typing_const_iv; )
		newCONSTSUB(typing_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = flags_const_iv + sizeof(flags_const_iv) / sizeof(flags_const_iv[0]); civ-- > flags_const_iv; )
		newCONSTSUB(flags_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = cbflags_const_iv + sizeof(cbflags_const_iv) / sizeof(cbflags_const_iv[0]); civ-- > cbflags_const_iv; )
		newCONSTSUB(cbflags_stash, (char *)civ->name, newSViv(civ->iv));
}

#line 1734 "Conversation.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

