/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Debug.xs. Do not edit this file, edit Debug.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Debug.xs"
#include "module.h"

#line 13 "Debug.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 155 "Debug.c"

XS_EUPXS(XS_Purple__Debug_purple_debug); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_purple_debug)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "level, category, string");
    {
	Purple__DebugLevel	level = (Purple__DebugLevel)SvIV(ST(0))
;
	const char *	category = (const char *)SvPV_nolen(ST(1))
;
	const char *	string = (const char *)SvPV_nolen(ST(2))
;
#line 30 "Debug.xs"
	purple_debug(level, category, "%s", string);
#line 172 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Debug_misc); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_misc)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0))
;
	const char *	string = (const char *)SvPV_nolen(ST(1))
;
#line 37 "Debug.xs"
	purple_debug_misc(category, "%s", string);
#line 191 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Debug_info); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_info)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0))
;
	const char *	string = (const char *)SvPV_nolen(ST(1))
;
#line 44 "Debug.xs"
	purple_debug_info(category, "%s", string);
#line 210 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Debug_warning); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_warning)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0))
;
	const char *	string = (const char *)SvPV_nolen(ST(1))
;
#line 51 "Debug.xs"
	purple_debug_warning(category, "%s", string);
#line 229 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Debug_error); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_error)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0))
;
	const char *	string = (const char *)SvPV_nolen(ST(1))
;
#line 58 "Debug.xs"
	purple_debug_error(category, "%s", string);
#line 248 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Debug_fatal); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_fatal)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "category, string");
    {
	const char *	category = (const char *)SvPV_nolen(ST(0))
;
	const char *	string = (const char *)SvPV_nolen(ST(1))
;
#line 65 "Debug.xs"
	purple_debug_fatal(category, "%s", string);
#line 267 "Debug.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Debug_set_enabled); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_set_enabled)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "enabled");
    {
	gboolean	enabled = (bool)SvTRUE(ST(0))
;

	purple_debug_set_enabled(enabled);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Debug_is_enabled); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Debug_is_enabled)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	gboolean	RETVAL;

	RETVAL = purple_debug_is_enabled();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Purple__Debug); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Purple__Debug)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Purple::Debug::purple_debug", XS_Purple__Debug_purple_debug, file, "$$$");
        (void)newXSproto_portable("Purple::Debug::misc", XS_Purple__Debug_misc, file, "$$");
        (void)newXSproto_portable("Purple::Debug::info", XS_Purple__Debug_info, file, "$$");
        (void)newXSproto_portable("Purple::Debug::warning", XS_Purple__Debug_warning, file, "$$");
        (void)newXSproto_portable("Purple::Debug::error", XS_Purple__Debug_error, file, "$$");
        (void)newXSproto_portable("Purple::Debug::fatal", XS_Purple__Debug_fatal, file, "$$");
        (void)newXSproto_portable("Purple::Debug::set_enabled", XS_Purple__Debug_set_enabled, file, "$");
        (void)newXSproto_portable("Purple::Debug::is_enabled", XS_Purple__Debug_is_enabled, file, "");

    /* Initialisation Section */

#line 7 "Debug.xs"
{
	HV *stash = gv_stashpv("Purple::Debug", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_DEBUG_##name}
		const_iv(ALL),
		const_iv(MISC),
		const_iv(INFO),
		const_iv(WARNING),
		const_iv(ERROR),
		const_iv(FATAL),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 354 "Debug.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

