/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Log.xs. Do not edit this file, edit Log.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Log.xs"
#include "module.h"

#line 13 "Log.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 155 "Log.c"

XS_EUPXS(XS_Purple__Log_get_handle); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_get_handle)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_log_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Log_common_sizer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_common_sizer)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "log");
    {
	Purple__Log	log = purple_perl_ref_object(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_log_common_sizer(log);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Log_common_writer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_common_writer)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "log, ext");
    {
	Purple__Log	log = purple_perl_ref_object(ST(0))
;
	const char *	ext = (const char *)SvPV_nolen(ST(1))
;

	purple_log_common_writer(log, ext);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Log_compare); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_compare)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "y, z");
    {
	gconstpointer	y = INT2PTR(gconstpointer,SvIV(ST(0)))
;
	gconstpointer	z = INT2PTR(gconstpointer,SvIV(ST(1)))
;
	gint	RETVAL;
	dXSTARG;

	RETVAL = purple_log_compare(y, z);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Log_free); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_free)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "log");
    {
	Purple__Log	log = purple_perl_ref_object(ST(0))
;

	purple_log_free(log);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Log_get_log_dir); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_get_log_dir)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "type, name, account");
    {
	Purple__LogType	type = (Purple__LogType)SvIV(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;
	Purple__Account	account = purple_perl_ref_object(ST(2))
;
	gchar_own *	RETVAL;

	RETVAL = purple_log_get_log_dir(type, name, account);
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Log_get_log_sets); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_get_log_sets)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 60 "Log.xs"
	GHashTable *l;
#line 287 "Log.c"
#line 62 "Log.xs"
	l = purple_log_get_log_sets();
	XPUSHs(sv_2mortal(purple_perl_bless_object(l, "GHashTable")));
#line 291 "Log.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Log_get_logs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_get_logs)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "type, name, account");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__LogType	type = (Purple__LogType)SvIV(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;
	Purple__Account	account = purple_perl_ref_object(ST(2))
;
#line 71 "Log.xs"
	GList *l, *ll;
#line 315 "Log.c"
#line 73 "Log.xs"
	ll = purple_log_get_logs(type, name, account);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Log")));
	}
	/* We can free the list here but the script needs to free the
	 * Purple::Log 'objects' itself. */
	g_list_free(ll);
#line 324 "Log.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Log_get_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_get_size)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "log");
    {
	Purple__Log	log = purple_perl_ref_object(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_log_get_size(log);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Log_get_system_logs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_get_system_logs)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "account");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Account	account = purple_perl_ref_object(ST(0))
;
#line 89 "Log.xs"
	GList *l, *ll;
#line 363 "Log.c"
#line 91 "Log.xs"
	ll = purple_log_get_system_logs(account);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Log")));
	}
	/* We can free the list here but the script needs to free the
	 * Purple::Log 'objects' itself. */
	g_list_free(ll);
#line 372 "Log.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Log_get_total_size); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_get_total_size)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "type, name, account");
    {
	Purple__LogType	type = (Purple__LogType)SvIV(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;
	Purple__Account	account = purple_perl_ref_object(ST(2))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_log_get_total_size(type, name, account);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Log_logger_free); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_logger_free)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "logger");
    {
	Purple__Log__Logger	logger = purple_perl_ref_object(ST(0))
;

	purple_log_logger_free(logger);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Log_logger_get_options); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_logger_get_options)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 112 "Log.xs"
	GList *l, *ll;
#line 429 "Log.c"
#line 114 "Log.xs"
	/* This might want to be massaged to a hash, since that's essentially
	 * what the key/value list is emulating. */
	for (l = ll = purple_log_logger_get_options(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(newSVpv(l->data, 0)));
	}
	g_list_free(ll);
#line 437 "Log.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Log_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_read)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "log, flags");
    {
	Purple__Log	log = purple_perl_ref_object(ST(0))
;
	Purple__Log__ReadFlags	flags = purple_perl_ref_object(ST(1))
;
	gchar_own *	RETVAL;

	RETVAL = purple_log_read(log, flags);
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Log_set_compare); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Log_set_compare)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "y, z");
    {
	gconstpointer	y = INT2PTR(gconstpointer,SvIV(ST(0)))
;
	gconstpointer	z = INT2PTR(gconstpointer,SvIV(ST(1)))
;
	gint	RETVAL;
	dXSTARG;

	RETVAL = purple_log_set_compare(y, z);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Purple__Log); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Purple__Log)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Purple::Log::get_handle", XS_Purple__Log_get_handle, file, "");
        (void)newXSproto_portable("Purple::Log::common_sizer", XS_Purple__Log_common_sizer, file, "$");
        (void)newXSproto_portable("Purple::Log::common_writer", XS_Purple__Log_common_writer, file, "$$");
        (void)newXSproto_portable("Purple::Log::compare", XS_Purple__Log_compare, file, "$$");
        (void)newXSproto_portable("Purple::Log::free", XS_Purple__Log_free, file, "$");
        (void)newXSproto_portable("Purple::Log::get_log_dir", XS_Purple__Log_get_log_dir, file, "$$$");
        (void)newXSproto_portable("Purple::Log::get_log_sets", XS_Purple__Log_get_log_sets, file, "");
        (void)newXSproto_portable("Purple::Log::get_logs", XS_Purple__Log_get_logs, file, "$$$");
        (void)newXSproto_portable("Purple::Log::get_size", XS_Purple__Log_get_size, file, "$");
        (void)newXSproto_portable("Purple::Log::get_system_logs", XS_Purple__Log_get_system_logs, file, "$");
        (void)newXSproto_portable("Purple::Log::get_total_size", XS_Purple__Log_get_total_size, file, "$$$");
        (void)newXSproto_portable("Purple::Log::logger_free", XS_Purple__Log_logger_free, file, "$");
        (void)newXSproto_portable("Purple::Log::logger_get_options", XS_Purple__Log_logger_get_options, file, "");
        (void)newXSproto_portable("Purple::Log::read", XS_Purple__Log_read, file, "$$");
        (void)newXSproto_portable("Purple::Log::set_compare", XS_Purple__Log_set_compare, file, "$$");

    /* Initialisation Section */

#line 7 "Log.xs"
{
	HV *type_stash = gv_stashpv("Purple::Log::Type", 1);
	HV *flags_stash = gv_stashpv("Purple::Log::ReadFlags", 1);

	static const constiv *civ, type_const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_LOG_##name}
		const_iv(IM),
		const_iv(CHAT),
		const_iv(SYSTEM),
	};
	static const constiv flags_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_LOG_READ_##name}
		const_iv(NO_NEWLINE),
	};

	for (civ = type_const_iv + sizeof(type_const_iv) / sizeof(type_const_iv[0]); civ-- > type_const_iv; )
		newCONSTSUB(type_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = flags_const_iv + sizeof(flags_const_iv) / sizeof(flags_const_iv[0]); civ-- > flags_const_iv; )
		newCONSTSUB(flags_stash, (char *)civ->name, newSViv(civ->iv));
}

#line 552 "Log.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

