/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Proxy.xs. Do not edit this file, edit Proxy.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Proxy.xs"
#include "module.h"

#line 13 "Proxy.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 155 "Proxy.c"

XS_EUPXS(XS_Purple__Proxy_get_handle); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Proxy_get_handle)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_proxy_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__ProxyInfo_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;

	purple_proxy_info_destroy(info);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__ProxyInfo_get_host); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_get_host)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_host(info);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__ProxyInfo_get_password); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_get_password)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_password(info);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__ProxyInfo_get_port); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_get_port)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_port(info);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__ProxyInfo_get_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_get_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	Purple__ProxyType	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_type(info);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__ProxyInfo_get_username); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_get_username)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "info");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_proxy_info_get_username(info);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__ProxyInfo_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_new)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__ProxyInfo	RETVAL;

	RETVAL = purple_proxy_info_new();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::ProxyInfo");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__ProxyInfo_set_host); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_set_host)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "info, host");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	const char *	host = (const char *)SvPV_nolen(ST(1))
;

	purple_proxy_info_set_host(info, host);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__ProxyInfo_set_password); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_set_password)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "info, password");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	const char *	password = (const char *)SvPV_nolen(ST(1))
;

	purple_proxy_info_set_password(info, password);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__ProxyInfo_set_port); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_set_port)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "info, port");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	int	port = (int)SvIV(ST(1))
;

	purple_proxy_info_set_port(info, port);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__ProxyInfo_set_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_set_type)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "info, type");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	Purple__ProxyType	type = (Purple__ProxyType)SvIV(ST(1))
;

	purple_proxy_info_set_type(info, type);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__ProxyInfo_set_username); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__ProxyInfo_set_username)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "info, username");
    {
	Purple__ProxyInfo	info = purple_perl_ref_object(ST(0))
;
	const char *	username = (const char *)SvPV_nolen(ST(1))
;

	purple_proxy_info_set_username(info, username);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Proxy_global_proxy_get_info); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Proxy_global_proxy_get_info)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__ProxyInfo	RETVAL;

	RETVAL = purple_global_proxy_get_info();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::ProxyInfo");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Purple__Proxy); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Purple__Proxy)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Purple::Proxy::get_handle", XS_Purple__Proxy_get_handle, file, "");
        (void)newXSproto_portable("Purple::ProxyInfo::destroy", XS_Purple__ProxyInfo_destroy, file, "$");
        (void)newXSproto_portable("Purple::ProxyInfo::get_host", XS_Purple__ProxyInfo_get_host, file, "$");
        (void)newXSproto_portable("Purple::ProxyInfo::get_password", XS_Purple__ProxyInfo_get_password, file, "$");
        (void)newXSproto_portable("Purple::ProxyInfo::get_port", XS_Purple__ProxyInfo_get_port, file, "$");
        (void)newXSproto_portable("Purple::ProxyInfo::get_type", XS_Purple__ProxyInfo_get_type, file, "$");
        (void)newXSproto_portable("Purple::ProxyInfo::get_username", XS_Purple__ProxyInfo_get_username, file, "$");
        (void)newXSproto_portable("Purple::ProxyInfo::new", XS_Purple__ProxyInfo_new, file, "");
        (void)newXSproto_portable("Purple::ProxyInfo::set_host", XS_Purple__ProxyInfo_set_host, file, "$$");
        (void)newXSproto_portable("Purple::ProxyInfo::set_password", XS_Purple__ProxyInfo_set_password, file, "$$");
        (void)newXSproto_portable("Purple::ProxyInfo::set_port", XS_Purple__ProxyInfo_set_port, file, "$$");
        (void)newXSproto_portable("Purple::ProxyInfo::set_type", XS_Purple__ProxyInfo_set_type, file, "$$");
        (void)newXSproto_portable("Purple::ProxyInfo::set_username", XS_Purple__ProxyInfo_set_username, file, "$$");
        (void)newXSproto_portable("Purple::Proxy::global_proxy_get_info", XS_Purple__Proxy_global_proxy_get_info, file, "");

    /* Initialisation Section */

#line 7 "Proxy.xs"
{
	HV *stash = gv_stashpv("Purple::ProxyType", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_PROXY_##name}
		const_iv(USE_GLOBAL),
		const_iv(NONE),
		const_iv(HTTP),
		const_iv(SOCKS4),
		const_iv(SOCKS5),
		const_iv(USE_ENVVAR),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 463 "Proxy.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

