/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Smiley.xs. Do not edit this file, edit Smiley.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Smiley.xs"
#include "module.h"

#line 13 "Smiley.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 155 "Smiley.c"

XS_EUPXS(XS_Purple__Smiley_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "img, shortcut");
    {
	Purple__StoredImage	img = purple_perl_ref_object(ST(0))
;
	const char *	shortcut = (const char *)SvPV_nolen(ST(1))
;
	Purple__Smiley	RETVAL;

	RETVAL = purple_smiley_new(img, shortcut);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_new_from_file); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_new_from_file)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "shortcut, filepath");
    {
	const char *	shortcut = (const char *)SvPV_nolen(ST(0))
;
	const char *	filepath = (const char *)SvPV_nolen(ST(1))
;
	Purple__Smiley	RETVAL;

	RETVAL = purple_smiley_new_from_file(shortcut, filepath);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_delete); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_delete)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;

	purple_smiley_delete(smiley);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Smiley_set_shortcut); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_set_shortcut)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "smiley, shortcut");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	const char *	shortcut = (const char *)SvPV_nolen(ST(1))
;
	gboolean	RETVAL;

	RETVAL = purple_smiley_set_shortcut(smiley, shortcut);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_set_data); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_set_data)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "smiley, data, data_len");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	guchar *	data = (guchar *)SvPV_nolen(ST(1))
;
	size_t	data_len = (size_t)SvUV(ST(2))
;

	purple_smiley_set_data(smiley, data, data_len);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Smiley_get_shortcut); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_get_shortcut)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_shortcut(smiley);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_get_checksum); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_get_checksum)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_checksum(smiley);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_get_stored_image); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_get_stored_image)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	Purple__StoredImage	RETVAL;

	RETVAL = purple_smiley_get_stored_image(smiley);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StoredImage");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_get_data); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_get_data)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "smiley, len");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	size_t *	len = INT2PTR(size_t *,SvIV(ST(1)))
;
	gconstpointer	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_data(smiley, len);
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_get_extension); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_get_extension)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smiley_get_extension(smiley);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smiley_get_full_path); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smiley_get_full_path)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "smiley");
    {
	Purple__Smiley	smiley = purple_perl_ref_object(ST(0))
;
	gchar_own *	RETVAL;

	RETVAL = purple_smiley_get_full_path(smiley);
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smileys_get_all); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smileys_get_all)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 64 "Smiley.xs"
    GList *l;
#line 388 "Smiley.c"
#line 66 "Smiley.xs"
    for (l = purple_smileys_get_all(); l != NULL; l = g_list_delete_link(l, l)) {
        XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Smiley")));
    }
#line 393 "Smiley.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Smileys_find_by_shortcut); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smileys_find_by_shortcut)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "shortcut");
    {
	const char *	shortcut = (const char *)SvPV_nolen(ST(0))
;
	Purple__Smiley	RETVAL;

	RETVAL = purple_smileys_find_by_shortcut(shortcut);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smileys_find_by_checksum); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smileys_find_by_checksum)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "checksum");
    {
	const char *	checksum = (const char *)SvPV_nolen(ST(0))
;
	Purple__Smiley	RETVAL;

	RETVAL = purple_smileys_find_by_checksum(checksum);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Smiley");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Smileys_get_storing_dir); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Smileys_get_storing_dir)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_smileys_get_storing_dir();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Purple__Smiley); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Purple__Smiley)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Purple::Smiley::new", XS_Purple__Smiley_new, file, "$$");
        (void)newXSproto_portable("Purple::Smiley::new_from_file", XS_Purple__Smiley_new_from_file, file, "$$");
        (void)newXSproto_portable("Purple::Smiley::delete", XS_Purple__Smiley_delete, file, "$");
        (void)newXSproto_portable("Purple::Smiley::set_shortcut", XS_Purple__Smiley_set_shortcut, file, "$$");
        (void)newXSproto_portable("Purple::Smiley::set_data", XS_Purple__Smiley_set_data, file, "$$$");
        (void)newXSproto_portable("Purple::Smiley::get_shortcut", XS_Purple__Smiley_get_shortcut, file, "$");
        (void)newXSproto_portable("Purple::Smiley::get_checksum", XS_Purple__Smiley_get_checksum, file, "$");
        (void)newXSproto_portable("Purple::Smiley::get_stored_image", XS_Purple__Smiley_get_stored_image, file, "$");
        (void)newXSproto_portable("Purple::Smiley::get_data", XS_Purple__Smiley_get_data, file, "$$");
        (void)newXSproto_portable("Purple::Smiley::get_extension", XS_Purple__Smiley_get_extension, file, "$");
        (void)newXSproto_portable("Purple::Smiley::get_full_path", XS_Purple__Smiley_get_full_path, file, "$");
        (void)newXSproto_portable("Purple::Smileys::get_all", XS_Purple__Smileys_get_all, file, "");
        (void)newXSproto_portable("Purple::Smileys::find_by_shortcut", XS_Purple__Smileys_find_by_shortcut, file, "$");
        (void)newXSproto_portable("Purple::Smileys::find_by_checksum", XS_Purple__Smileys_find_by_checksum, file, "$");
        (void)newXSproto_portable("Purple::Smileys::get_storing_dir", XS_Purple__Smileys_get_storing_dir, file, "");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

