/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of Status.xs. Do not edit this file, edit Status.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Status.xs"
#include "module.h"

/* TODO

void
purple_status_type_add_attrs(status_type, id, name, value, purple_status_type_add_attrs)
	Purple::StatusType status_type
	const char *id
	const char *name
	Purple::Value value
	...

Purple::StatusType
purple_status_type_new_with_attrs(primitive, id, name, saveable, user_settable, independent, attr_id, attr_name, attr_value, purple_status_type_new_with_attrs)
	Purple::StatusPrimitive primitive
	const char *id
	const char *name
	gboolean saveable
	gboolean user_settable
	gboolean independent
	const char *attr_id
	const char *attr_name
	Purple::Value attr_value
	...

*/

/* These break on faceprint's amd64 box
void
purple_status_type_add_attrs_vargs(status_type, args)
	Purple::StatusType status_type
	va_list args

void
purple_status_set_active_with_attrs(status, active, args)
	Purple::Status status
	gboolean active
	va_list args

	*/

#line 52 "Status.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 194 "Status.c"

XS_EUPXS(XS_Purple__Presence_add_list); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_add_list)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence, source_list");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	SV *	source_list = ST(1)
;
#line 82 "Status.xs"
	GList *t_GL;
	int i, t_len;
#line 212 "Status.c"
#line 85 "Status.xs"
	t_GL = NULL;
	t_len = av_len((AV *)SvRV(source_list));

	for (i = 0; i <= t_len; i++) {
		t_GL = g_list_append(t_GL, SvPVutf8_nolen(*av_fetch((AV *)SvRV(source_list), i, 0)));
	}
	purple_presence_add_list(presence, t_GL);
	g_list_free(t_GL);
#line 222 "Status.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Presence_add_status); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_add_status)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence, status");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	Purple__Status	status = purple_perl_ref_object(ST(1))
;

	purple_presence_add_status(presence, status);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Presence_compare); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_compare)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence1, presence2");
    {
	Purple__Presence	presence1 = purple_perl_ref_object(ST(0))
;
	Purple__Presence	presence2 = purple_perl_ref_object(ST(1))
;
	gint	RETVAL;
	dXSTARG;

	RETVAL = purple_presence_compare(presence1, presence2);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;

	purple_presence_destroy(presence);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Presence_get_account); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_account)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	Purple__Account	RETVAL;

	RETVAL = purple_presence_get_account(presence);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Account");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_active_status); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_active_status)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	Purple__Status	RETVAL;

	RETVAL = purple_presence_get_active_status(presence);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Status");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_chat_user); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_chat_user)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_presence_get_chat_user(presence);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_context); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_context)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	Purple__PresenceContext	RETVAL;
	dXSTARG;

	RETVAL = purple_presence_get_context(presence);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_conversation); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_conversation)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	Purple__Conversation	RETVAL;

	RETVAL = purple_presence_get_conversation(presence);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Conversation");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_idle_time); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_idle_time)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	time_t	RETVAL;
	dXSTARG;

	RETVAL = purple_presence_get_idle_time(presence);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_login_time); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_login_time)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	time_t	RETVAL;
	dXSTARG;

	RETVAL = purple_presence_get_login_time(presence);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_status); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_status)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence, status_id");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	const char *	status_id = (const char *)SvPV_nolen(ST(1))
;
	Purple__Status	RETVAL;

	RETVAL = purple_presence_get_status(presence, status_id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Status");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_get_statuses); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_get_statuses)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
#line 145 "Status.xs"
	GList *l;
#line 451 "Status.c"
#line 147 "Status.xs"
	for (l = purple_presence_get_statuses(presence); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Status")));
	}
#line 456 "Status.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__Presence_is_available); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_is_available)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_presence_is_available(presence);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_is_idle); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_is_idle)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_presence_is_idle(presence);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_is_online); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_is_online)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "presence");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_presence_is_online(presence);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_is_status_active); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_is_status_active)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence, status_id");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	const char *	status_id = (const char *)SvPV_nolen(ST(1))
;
	gboolean	RETVAL;

	RETVAL = purple_presence_is_status_active(presence, status_id);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_is_status_primitive_active); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_is_status_primitive_active)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence, primitive");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	Purple__StatusPrimitive	primitive = (Purple__StatusPrimitive)SvIV(ST(1))
;
	gboolean	RETVAL;

	RETVAL = purple_presence_is_status_primitive_active(presence, primitive);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "context");
    {
	Purple__PresenceContext	context = (Purple__PresenceContext)SvIV(ST(0))
;
	Purple__Presence	RETVAL;

	RETVAL = purple_presence_new(context);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Presence");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_new_for_account); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_new_for_account)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "account");
    {
	Purple__Account	account = purple_perl_ref_object(ST(0))
;
	Purple__Presence	RETVAL;

	RETVAL = purple_presence_new_for_account(account);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Presence");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_new_for_buddy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_new_for_buddy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "buddy");
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0))
;
	Purple__Presence	RETVAL;

	RETVAL = purple_presence_new_for_buddy(buddy);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Presence");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_new_for_conv); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_new_for_conv)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "conv");
    {
	Purple__Conversation	conv = purple_perl_ref_object(ST(0))
;
	Purple__Presence	RETVAL;

	RETVAL = purple_presence_new_for_conv(conv);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Presence");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Presence_set_idle); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_set_idle)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "presence, idle, idle_time");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	gboolean	idle = (bool)SvTRUE(ST(1))
;
	time_t	idle_time = (time_t)SvIV(ST(2))
;

	purple_presence_set_idle(presence, idle, idle_time);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Presence_set_login_time); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_set_login_time)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence, login_time");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	time_t	login_time = (time_t)SvIV(ST(1))
;

	purple_presence_set_login_time(presence, login_time);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Presence_set_status_active); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_set_status_active)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "presence, status_id, active");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	const char *	status_id = (const char *)SvPV_nolen(ST(1))
;
	gboolean	active = (bool)SvTRUE(ST(2))
;

	purple_presence_set_status_active(presence, status_id, active);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Presence_switch_status); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Presence_switch_status)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "presence, status_id");
    {
	Purple__Presence	presence = purple_perl_ref_object(ST(0))
;
	const char *	status_id = (const char *)SvPV_nolen(ST(1))
;

	purple_presence_switch_status(presence, status_id);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Primitive_get_id_from_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Primitive_get_id_from_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "type");
    {
	Purple__StatusPrimitive	type = (Purple__StatusPrimitive)SvIV(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_primitive_get_id_from_type(type);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Primitive_get_name_from_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Primitive_get_name_from_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "type");
    {
	Purple__StatusPrimitive	type = (Purple__StatusPrimitive)SvIV(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_primitive_get_name_from_type(type);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Primitive_get_type_from_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Primitive_get_type_from_id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "id");
    {
	const char *	id = (const char *)SvPV_nolen(ST(0))
;
	Purple__StatusPrimitive	RETVAL;
	dXSTARG;

	RETVAL = purple_primitive_get_type_from_id(id);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusAttr_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusAttr_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "attr");
    {
	Purple__StatusAttr	attr = purple_perl_ref_object(ST(0))
;

	purple_status_attr_destroy(attr);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__StatusAttr_get_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusAttr_get_id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "attr");
    {
	Purple__StatusAttr	attr = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_attr_get_id(attr);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusAttr_get_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusAttr_get_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "attr");
    {
	Purple__StatusAttr	attr = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_attr_get_name(attr);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusAttr_get_value); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusAttr_get_value)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "attr");
    {
	Purple__StatusAttr	attr = purple_perl_ref_object(ST(0))
;
	Purple__Value	RETVAL;

	RETVAL = purple_status_attr_get_value(attr);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Value");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusAttr_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusAttr_new)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "id, name, value_type");
    {
	const char *	id = (const char *)SvPV_nolen(ST(0))
;
	const char *	name = (const char *)SvPV_nolen(ST(1))
;
	Purple__Value	value_type = purple_perl_ref_object(ST(2))
;
	Purple__StatusAttr	RETVAL;

	RETVAL = purple_status_attr_new(id, name, value_type);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StatusAttr");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_compare); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_compare)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status1, status2");
    {
	Purple__Status	status1 = purple_perl_ref_object(ST(0))
;
	Purple__Status	status2 = purple_perl_ref_object(ST(1))
;
	gint	RETVAL;
	dXSTARG;

	RETVAL = purple_status_compare(status1, status2);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;

	purple_status_destroy(status);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Status_get_attr_boolean); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_attr_boolean)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status, id");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	gboolean	RETVAL;

	RETVAL = purple_status_get_attr_boolean(status, id);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_attr_int); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_attr_int)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status, id");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_status_get_attr_int(status, id);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_attr_string); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_attr_string)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status, id");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_get_attr_string(status, id);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_attr_value); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_attr_value)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status, id");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	Purple__Value	RETVAL;

	RETVAL = purple_status_get_attr_value(status, id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Value");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_handle); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_handle)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_status_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_get_id(status);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_get_name(status);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_presence); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_presence)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	Purple__Presence	RETVAL;

	RETVAL = purple_status_get_presence(status);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Presence");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_get_type); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_get_type)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	Purple__StatusType	RETVAL;

	RETVAL = purple_status_get_type(status);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StatusType");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_is_active); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_is_active)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_is_active(status);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_is_available); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_is_available)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_is_available(status);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_is_exclusive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_is_exclusive)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_is_exclusive(status);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_is_independent); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_is_independent)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_is_independent(status);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_is_online); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_is_online)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_is_online(status);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status_type, presence");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	Purple__Presence	presence = purple_perl_ref_object(ST(1))
;
	Purple__Status	RETVAL;

	RETVAL = purple_status_new(status_type, presence);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Status");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__Status_set_active); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_set_active)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status, active");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	gboolean	active = (bool)SvTRUE(ST(1))
;

	purple_status_set_active(status, active);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Status_set_attr_boolean); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_set_attr_boolean)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "status, id, value");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	gboolean	value = (bool)SvTRUE(ST(2))
;

	purple_status_set_attr_boolean(status, id, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__Status_set_attr_string); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__Status_set_attr_string)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "status, id, value");
    {
	Purple__Status	status = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	const char *	value = (const char *)SvPV_nolen(ST(2))
;

	purple_status_set_attr_string(status, id, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__StatusType_add_attr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_add_attr)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "status_type, id, name, value");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	const char *	name = (const char *)SvPV_nolen(ST(2))
;
	Purple__Value	value = purple_perl_ref_object(ST(3))
;

	purple_status_type_add_attr(status_type, id, name, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__StatusType_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;

	purple_status_type_destroy(status_type);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Purple__StatusType_get_attr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_get_attr)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status_type, id");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	Purple__StatusAttr	RETVAL;

	RETVAL = purple_status_type_get_attr(status_type, id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StatusAttr");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_get_attrs); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_get_attrs)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
#line 367 "Status.xs"
	GList *l;
#line 1327 "Status.c"
#line 369 "Status.xs"
	for (l = purple_status_type_get_attrs(status_type); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::StatusAttr")));
	}
#line 1332 "Status.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_Purple__StatusType_find_with_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_find_with_id)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status_types, id");
    {
	SV *	status_types = ST(0)
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
#line 378 "Status.xs"
	GList *t_GL;
	int i, t_len;
#line 1353 "Status.c"
	Purple__StatusType	RETVAL;
#line 381 "Status.xs"
	t_GL = NULL;
	t_len = av_len((AV *)SvRV(status_types));

	for (i = 0; i <= t_len; i++) {
		t_GL = g_list_append(t_GL, SvPVutf8_nolen(*av_fetch((AV *)SvRV(status_types), i, 0)));
	}
	RETVAL = (PurpleStatusType *)purple_status_type_find_with_id(t_GL, id);
	g_list_free(t_GL);
#line 1364 "Status.c"
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StatusType");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_get_id); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_get_id)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_type_get_id(status_type);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_get_name); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_get_name)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_type_get_name(status_type);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_get_primary_attr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_get_primary_attr)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_status_type_get_primary_attr(status_type);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_get_primitive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_get_primitive)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	Purple__StatusPrimitive	RETVAL;
	dXSTARG;

	RETVAL = purple_status_type_get_primitive(status_type);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_is_available); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_is_available)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_type_is_available(status_type);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_is_exclusive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_is_exclusive)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_type_is_exclusive(status_type);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_is_independent); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_is_independent)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_type_is_independent(status_type);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_is_saveable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_is_saveable)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_type_is_saveable(status_type);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_is_user_settable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_is_user_settable)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_type");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	gboolean	RETVAL;

	RETVAL = purple_status_type_is_user_settable(status_type);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_new)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "primitive, id, name, user_settable");
    {
	Purple__StatusPrimitive	primitive = (Purple__StatusPrimitive)SvIV(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	const char *	name = (const char *)SvPV_nolen(ST(2))
;
	gboolean	user_settable = (bool)SvTRUE(ST(3))
;
	Purple__StatusType	RETVAL;

	RETVAL = purple_status_type_new(primitive, id, name, user_settable);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StatusType");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_new_full); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_new_full)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "primitive, id, name, saveable, user_settable, independent");
    {
	Purple__StatusPrimitive	primitive = (Purple__StatusPrimitive)SvIV(ST(0))
;
	const char *	id = (const char *)SvPV_nolen(ST(1))
;
	const char *	name = (const char *)SvPV_nolen(ST(2))
;
	gboolean	saveable = (bool)SvTRUE(ST(3))
;
	gboolean	user_settable = (bool)SvTRUE(ST(4))
;
	gboolean	independent = (bool)SvTRUE(ST(5))
;
	Purple__StatusType	RETVAL;

	RETVAL = purple_status_type_new_full(primitive, id, name, saveable, user_settable, independent);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::StatusType");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Purple__StatusType_set_primary_attr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Purple__StatusType_set_primary_attr)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status_type, attr_id");
    {
	Purple__StatusType	status_type = purple_perl_ref_object(ST(0))
;
	const char *	attr_id = (const char *)SvPV_nolen(ST(1))
;

	purple_status_type_set_primary_attr(status_type, attr_id);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Purple__Status); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Purple__Status)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Purple::Presence::add_list", XS_Purple__Presence_add_list, file, "$$");
        (void)newXSproto_portable("Purple::Presence::add_status", XS_Purple__Presence_add_status, file, "$$");
        (void)newXSproto_portable("Purple::Presence::compare", XS_Purple__Presence_compare, file, "$$");
        (void)newXSproto_portable("Purple::Presence::destroy", XS_Purple__Presence_destroy, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_account", XS_Purple__Presence_get_account, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_active_status", XS_Purple__Presence_get_active_status, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_chat_user", XS_Purple__Presence_get_chat_user, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_context", XS_Purple__Presence_get_context, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_conversation", XS_Purple__Presence_get_conversation, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_idle_time", XS_Purple__Presence_get_idle_time, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_login_time", XS_Purple__Presence_get_login_time, file, "$");
        (void)newXSproto_portable("Purple::Presence::get_status", XS_Purple__Presence_get_status, file, "$$");
        (void)newXSproto_portable("Purple::Presence::get_statuses", XS_Purple__Presence_get_statuses, file, "$");
        (void)newXSproto_portable("Purple::Presence::is_available", XS_Purple__Presence_is_available, file, "$");
        (void)newXSproto_portable("Purple::Presence::is_idle", XS_Purple__Presence_is_idle, file, "$");
        (void)newXSproto_portable("Purple::Presence::is_online", XS_Purple__Presence_is_online, file, "$");
        (void)newXSproto_portable("Purple::Presence::is_status_active", XS_Purple__Presence_is_status_active, file, "$$");
        (void)newXSproto_portable("Purple::Presence::is_status_primitive_active", XS_Purple__Presence_is_status_primitive_active, file, "$$");
        (void)newXSproto_portable("Purple::Presence::new", XS_Purple__Presence_new, file, "$");
        (void)newXSproto_portable("Purple::Presence::new_for_account", XS_Purple__Presence_new_for_account, file, "$");
        (void)newXSproto_portable("Purple::Presence::new_for_buddy", XS_Purple__Presence_new_for_buddy, file, "$");
        (void)newXSproto_portable("Purple::Presence::new_for_conv", XS_Purple__Presence_new_for_conv, file, "$");
        (void)newXSproto_portable("Purple::Presence::set_idle", XS_Purple__Presence_set_idle, file, "$$$");
        (void)newXSproto_portable("Purple::Presence::set_login_time", XS_Purple__Presence_set_login_time, file, "$$");
        (void)newXSproto_portable("Purple::Presence::set_status_active", XS_Purple__Presence_set_status_active, file, "$$$");
        (void)newXSproto_portable("Purple::Presence::switch_status", XS_Purple__Presence_switch_status, file, "$$");
        (void)newXSproto_portable("Purple::Primitive::get_id_from_type", XS_Purple__Primitive_get_id_from_type, file, "$");
        (void)newXSproto_portable("Purple::Primitive::get_name_from_type", XS_Purple__Primitive_get_name_from_type, file, "$");
        (void)newXSproto_portable("Purple::Primitive::get_type_from_id", XS_Purple__Primitive_get_type_from_id, file, "$");
        (void)newXSproto_portable("Purple::StatusAttr::destroy", XS_Purple__StatusAttr_destroy, file, "$");
        (void)newXSproto_portable("Purple::StatusAttr::get_id", XS_Purple__StatusAttr_get_id, file, "$");
        (void)newXSproto_portable("Purple::StatusAttr::get_name", XS_Purple__StatusAttr_get_name, file, "$");
        (void)newXSproto_portable("Purple::StatusAttr::get_value", XS_Purple__StatusAttr_get_value, file, "$");
        (void)newXSproto_portable("Purple::StatusAttr::new", XS_Purple__StatusAttr_new, file, "$$$");
        (void)newXSproto_portable("Purple::Status::compare", XS_Purple__Status_compare, file, "$$");
        (void)newXSproto_portable("Purple::Status::destroy", XS_Purple__Status_destroy, file, "$");
        (void)newXSproto_portable("Purple::Status::get_attr_boolean", XS_Purple__Status_get_attr_boolean, file, "$$");
        (void)newXSproto_portable("Purple::Status::get_attr_int", XS_Purple__Status_get_attr_int, file, "$$");
        (void)newXSproto_portable("Purple::Status::get_attr_string", XS_Purple__Status_get_attr_string, file, "$$");
        (void)newXSproto_portable("Purple::Status::get_attr_value", XS_Purple__Status_get_attr_value, file, "$$");
        (void)newXSproto_portable("Purple::Status::get_handle", XS_Purple__Status_get_handle, file, "");
        (void)newXSproto_portable("Purple::Status::get_id", XS_Purple__Status_get_id, file, "$");
        (void)newXSproto_portable("Purple::Status::get_name", XS_Purple__Status_get_name, file, "$");
        (void)newXSproto_portable("Purple::Status::get_presence", XS_Purple__Status_get_presence, file, "$");
        (void)newXSproto_portable("Purple::Status::get_type", XS_Purple__Status_get_type, file, "$");
        (void)newXSproto_portable("Purple::Status::is_active", XS_Purple__Status_is_active, file, "$");
        (void)newXSproto_portable("Purple::Status::is_available", XS_Purple__Status_is_available, file, "$");
        (void)newXSproto_portable("Purple::Status::is_exclusive", XS_Purple__Status_is_exclusive, file, "$");
        (void)newXSproto_portable("Purple::Status::is_independent", XS_Purple__Status_is_independent, file, "$");
        (void)newXSproto_portable("Purple::Status::is_online", XS_Purple__Status_is_online, file, "$");
        (void)newXSproto_portable("Purple::Status::new", XS_Purple__Status_new, file, "$$");
        (void)newXSproto_portable("Purple::Status::set_active", XS_Purple__Status_set_active, file, "$$");
        (void)newXSproto_portable("Purple::Status::set_attr_boolean", XS_Purple__Status_set_attr_boolean, file, "$$$");
        (void)newXSproto_portable("Purple::Status::set_attr_string", XS_Purple__Status_set_attr_string, file, "$$$");
        (void)newXSproto_portable("Purple::StatusType::add_attr", XS_Purple__StatusType_add_attr, file, "$$$$");
        (void)newXSproto_portable("Purple::StatusType::destroy", XS_Purple__StatusType_destroy, file, "$");
        (void)newXSproto_portable("Purple::StatusType::get_attr", XS_Purple__StatusType_get_attr, file, "$$");
        (void)newXSproto_portable("Purple::StatusType::get_attrs", XS_Purple__StatusType_get_attrs, file, "$");
        (void)newXSproto_portable("Purple::StatusType::find_with_id", XS_Purple__StatusType_find_with_id, file, "$$");
        (void)newXSproto_portable("Purple::StatusType::get_id", XS_Purple__StatusType_get_id, file, "$");
        (void)newXSproto_portable("Purple::StatusType::get_name", XS_Purple__StatusType_get_name, file, "$");
        (void)newXSproto_portable("Purple::StatusType::get_primary_attr", XS_Purple__StatusType_get_primary_attr, file, "$");
        (void)newXSproto_portable("Purple::StatusType::get_primitive", XS_Purple__StatusType_get_primitive, file, "$");
        (void)newXSproto_portable("Purple::StatusType::is_available", XS_Purple__StatusType_is_available, file, "$");
        (void)newXSproto_portable("Purple::StatusType::is_exclusive", XS_Purple__StatusType_is_exclusive, file, "$");
        (void)newXSproto_portable("Purple::StatusType::is_independent", XS_Purple__StatusType_is_independent, file, "$");
        (void)newXSproto_portable("Purple::StatusType::is_saveable", XS_Purple__StatusType_is_saveable, file, "$");
        (void)newXSproto_portable("Purple::StatusType::is_user_settable", XS_Purple__StatusType_is_user_settable, file, "$");
        (void)newXSproto_portable("Purple::StatusType::new", XS_Purple__StatusType_new, file, "$$$$");
        (void)newXSproto_portable("Purple::StatusType::new_full", XS_Purple__StatusType_new_full, file, "$$$$$$");
        (void)newXSproto_portable("Purple::StatusType::set_primary_attr", XS_Purple__StatusType_set_primary_attr, file, "$$");

    /* Initialisation Section */

#line 46 "Status.xs"
{
	HV *context_stash = gv_stashpv("Purple::Presence::Context", 1);
	HV *primitive_stash = gv_stashpv("Purple::Status::Primitive", 1);

	static const constiv *civ, context_const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_PRESENCE_CONTEXT_##name}
		const_iv(UNSET),
		const_iv(ACCOUNT),
		const_iv(CONV),
		const_iv(BUDDY),
	};
	static const constiv primitive_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_STATUS_##name}
		const_iv(UNSET),
		const_iv(OFFLINE),
		const_iv(AVAILABLE),
		const_iv(UNAVAILABLE),
		const_iv(INVISIBLE),
		const_iv(AWAY),
		const_iv(EXTENDED_AWAY),
		const_iv(MOBILE),
	};

	for (civ = context_const_iv + sizeof(context_const_iv) / sizeof(context_const_iv[0]); civ-- > context_const_iv; )
		newCONSTSUB(context_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = primitive_const_iv + sizeof(primitive_const_iv) / sizeof(primitive_const_iv[0]); civ-- > primitive_const_iv; )
		newCONSTSUB(primitive_stash, (char *)civ->name, newSViv(civ->iv));
}

#line 1740 "Status.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

