/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of GtkFt.xs. Do not edit this file, edit GtkFt.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "GtkFt.xs"
#include "gtkmodule.h"

#line 13 "GtkFt.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 155 "GtkFt.c"

XS_EUPXS(XS_Pidgin__Xfer_set_xfer_dialog); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer_set_xfer_dialog)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dialog");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0))
;

	pidgin_set_xfer_dialog(dialog);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__Xfer_get_xfer_dialog); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer_get_xfer_dialog)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	Pidgin__Xfer__Dialog	RETVAL;

	RETVAL = pidgin_get_xfer_dialog();
	ST(0) = purple_perl_bless_object(RETVAL, "Pidgin::Xfer::Dialog");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_new)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "class");
    {
	Pidgin__Xfer__Dialog	RETVAL;

	RETVAL = pidgin_xfer_dialog_new(/* void */);
	ST(0) = purple_perl_bless_object(RETVAL, "Pidgin::Xfer::Dialog");
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_destroy); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_destroy)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dialog");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0))
;

	pidgin_xfer_dialog_destroy(dialog);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_show); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_show)
{
    dVAR; dXSARGS;
    if (items < 0 || items > 1)
       croak_xs_usage(cv,  "dialog = NULL");
    {
	Pidgin__Xfer__Dialog	dialog;

	if (items < 1)
	    dialog = NULL;
	else {
	    dialog = purple_perl_ref_object(ST(0))
;
	}

	pidgin_xfer_dialog_show(dialog);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_hide); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_hide)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dialog");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0))
;

	pidgin_xfer_dialog_hide(dialog);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_add_xfer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_add_xfer)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0))
;
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1))
;

	pidgin_xfer_dialog_add_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_remove_xfer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_remove_xfer)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0))
;
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1))
;

	pidgin_xfer_dialog_remove_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_cancel_xfer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_cancel_xfer)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0))
;
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1))
;

	pidgin_xfer_dialog_cancel_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__Xfer__Dialog_update_xfer); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__Xfer__Dialog_update_xfer)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dialog, xfer");
    {
	Pidgin__Xfer__Dialog	dialog = purple_perl_ref_object(ST(0))
;
	Purple__Xfer	xfer = purple_perl_ref_object(ST(1))
;

	pidgin_xfer_dialog_update_xfer(dialog, xfer);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Pidgin__Xfer); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Pidgin__Xfer)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Pidgin::Xfer::set_xfer_dialog", XS_Pidgin__Xfer_set_xfer_dialog, file, "$");
        (void)newXSproto_portable("Pidgin::Xfer::get_xfer_dialog", XS_Pidgin__Xfer_get_xfer_dialog, file, "");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::new", XS_Pidgin__Xfer__Dialog_new, file, "$");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::destroy", XS_Pidgin__Xfer__Dialog_destroy, file, "$");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::show", XS_Pidgin__Xfer__Dialog_show, file, ";$");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::hide", XS_Pidgin__Xfer__Dialog_hide, file, "$");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::add_xfer", XS_Pidgin__Xfer__Dialog_add_xfer, file, "$$");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::remove_xfer", XS_Pidgin__Xfer__Dialog_remove_xfer, file, "$$");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::cancel_xfer", XS_Pidgin__Xfer__Dialog_cancel_xfer, file, "$$");
        (void)newXSproto_portable("Pidgin::Xfer::Dialog::update_xfer", XS_Pidgin__Xfer__Dialog_update_xfer, file, "$$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

