/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.16 from the
 * contents of GtkStatusBox.xs. Do not edit this file, edit GtkStatusBox.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "GtkStatusBox.xs"
#include "gtkmodule.h"

/* This can't work at the moment since I don't have a typemap for Gtk::Widget.
 * I thought about using the one from libgtk2-perl but wasn't sure how to go
 * about doing that.
Gtk::Widget
pidgin_status_box_new()

Gtk::Widget
pidgin_status_box_new_with_account(account)
	Purple::Account account

void
pidgin_status_box_add(status_box, type, pixbuf, text, sec_text, data)
	Pidgin::StatusBox status_box
	Pidgin::StatusBox::ItemType type
	GdkPixbuf pixbuf
	const char * text
	const char * sec_text
	gpointer data
*/

#line 33 "GtkStatusBox.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 175 "GtkStatusBox.c"

XS_EUPXS(XS_Pidgin__StatusBox_add_separator); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__StatusBox_add_separator)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_box");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0))
;

	pidgin_status_box_add_separator(status_box);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__StatusBox_set_connecting); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__StatusBox_set_connecting)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status_box, connecting");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0))
;
	gboolean	connecting = (bool)SvTRUE(ST(1))
;

	pidgin_status_box_set_connecting(status_box, connecting);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__StatusBox_pulse_connecting); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__StatusBox_pulse_connecting)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_box");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0))
;

	pidgin_status_box_pulse_connecting(status_box);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__StatusBox_set_buddy_icon); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__StatusBox_set_buddy_icon)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "status_box, img");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0))
;
	Purple__StoredImage	img = purple_perl_ref_object(ST(1))
;

	pidgin_status_box_set_buddy_icon(status_box, img);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Pidgin__StatusBox_get_message); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Pidgin__StatusBox_get_message)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "status_box");
    {
	Pidgin__StatusBox	status_box = purple_perl_ref_object(ST(0))
;
	gchar_own *	RETVAL;

	RETVAL = pidgin_status_box_get_message(status_box);
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Pidgin__StatusBox); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Pidgin__StatusBox)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        (void)newXSproto_portable("Pidgin::StatusBox::add_separator", XS_Pidgin__StatusBox_add_separator, file, "$");
        (void)newXSproto_portable("Pidgin::StatusBox::set_connecting", XS_Pidgin__StatusBox_set_connecting, file, "$$");
        (void)newXSproto_portable("Pidgin::StatusBox::pulse_connecting", XS_Pidgin__StatusBox_pulse_connecting, file, "$");
        (void)newXSproto_portable("Pidgin::StatusBox::set_buddy_icon", XS_Pidgin__StatusBox_set_buddy_icon, file, "$$");
        (void)newXSproto_portable("Pidgin::StatusBox::get_message", XS_Pidgin__StatusBox_get_message, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

